sudo: required
dist: trusty

services:

script:
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install --yes cmake make g++ clang perl libssl-dev libboost-dev g++-4.9
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo curl -O http://www.codesynthesis.com/download/odb/2.4/odb_2.4.0-1_amd64.deb
  - sudo dpkg -i odb_2.4.0-1_amd64.deb
  - sudo curl -O http://www.codesynthesis.com/download/odb/2.4/libodb-2.4.0.tar.gz
  - sudo tar -xvzf libodb-2.4.0.tar.gz
  - cd libodb-2.4.0/
  - sudo ./configure
  - sudo make
  - sudo make install
  -  cd ..
  - sudo curl -O http://www.codesynthesis.com/download/odb/2.4/libodb-sqlite-2.4.0.tar.gz
  - sudo tar -xvzf libodb-sqlite-2.4.0.tar.gz
  - cd libodb-sqlite-2.4.0/
  - sudo ./configure
  - sudo make
  - sudo make install
  -  cd ..
  - ls
  -  mkdir build
  - cd build
  - sudo  cmake  ..
  - sudo make
