sudo: required

services:
  - docker

script:
  - sudo docker run -it -v "$PWD:/repository" debian:testing sh -c "
      apt-get update &&
      apt-get install --yes cmake make g\+\+ clang perl libssl-dev libboost-thread-dev libboost-regex-dev libboost-date-time-dev libboost-filesystem-dev &&
      curl -O http://www.codesynthesis.com/download/odb/2.4/odb_2.4.0-1_i386.deb &&
      sudo dpkg -i odb_2.4.0-1_i386.deb &&
      curl -O http://www.codesynthesis.com/download/odb/2.4/libodb-sqlite-2.4.0.tar.gz &&
      tar -xvzf libodb-sqlite-2.4.0.tar.gz &&
      cd libodb-sqlite-2.4.0/ &&
      ./configure &&
      make &&
      make install &&
      cd .. &
      cd /repository && mkdir build && cd build &&
      scan-build cmake -DCMAKE_CXX_FLAGS=-Werror .. &&
      scan-build --status-bugs make &&
      rm -r * &&
      CXX=clang++ cmake -DCMAKE_CXX_FLAGS=-Werror .. &&
      make &&
      rm -r * &&
      CXX=g++ cmake -DCMAKE_CXX_FLAGS=-Werror .. &&
      make &&
      CTEST_OUTPUT_ON_FAILURE=1 make test
      "
