// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef USER_ODB_HPP
#define USER_ODB_HPP

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "User.hpp"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // User
  //
  template <>
  struct class_traits< ::User >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::User >
  {
    public:
    typedef ::User object_type;
    typedef ::User* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // User
  //
  template <typename A>
  struct query_columns< ::User, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // firebaseID
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    firebaseID_type_;

    static const firebaseID_type_ firebaseID;

    // lat
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    lat_type_;

    static const lat_type_ lat;

    // lng
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    lng_type_;

    static const lng_type_ lng;

    // minMagPreference
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    minMagPreference_type_;

    static const minMagPreference_type_ minMagPreference;

    // maxDistancePreference
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    maxDistancePreference_type_;

    static const maxDistancePreference_type_ maxDistancePreference;

    // minMillisNotificationDelay
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    minMillisNotificationDelay_type_;

    static const minMillisNotificationDelay_type_ minMillisNotificationDelay;

    // lastNotificationMillis
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    lastNotificationMillis_type_;

    static const lastNotificationMillis_type_ lastNotificationMillis;

    // receiveRealTimeNotification
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    receiveRealTimeNotification_type_;

    static const receiveRealTimeNotification_type_ receiveRealTimeNotification;

    // lastModify
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    lastModify_type_;

    static const lastModify_type_ lastModify;

    // secretKey
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    secretKey_type_;

    static const secretKey_type_ secretKey;
  };

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::id_type_
  query_columns< ::User, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::firebaseID_type_
  query_columns< ::User, id_sqlite, A >::
  firebaseID (A::table_name, "\"firebaseID\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::lat_type_
  query_columns< ::User, id_sqlite, A >::
  lat (A::table_name, "\"lat\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::lng_type_
  query_columns< ::User, id_sqlite, A >::
  lng (A::table_name, "\"lng\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::minMagPreference_type_
  query_columns< ::User, id_sqlite, A >::
  minMagPreference (A::table_name, "\"minMagPreference\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::maxDistancePreference_type_
  query_columns< ::User, id_sqlite, A >::
  maxDistancePreference (A::table_name, "\"maxDistancePreference\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::minMillisNotificationDelay_type_
  query_columns< ::User, id_sqlite, A >::
  minMillisNotificationDelay (A::table_name, "\"minMillisNotificationDelay\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::lastNotificationMillis_type_
  query_columns< ::User, id_sqlite, A >::
  lastNotificationMillis (A::table_name, "\"lastNotificationMillis\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::receiveRealTimeNotification_type_
  query_columns< ::User, id_sqlite, A >::
  receiveRealTimeNotification (A::table_name, "\"receiveRealTimeNotification\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::lastModify_type_
  query_columns< ::User, id_sqlite, A >::
  lastModify (A::table_name, "\"lastModify\"", 0);

  template <typename A>
  const typename query_columns< ::User, id_sqlite, A >::secretKey_type_
  query_columns< ::User, id_sqlite, A >::
  secretKey (A::table_name, "\"secretKey\"", 0);

  template <typename A>
  struct pointer_query_columns< ::User, id_sqlite, A >:
    query_columns< ::User, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::User, id_sqlite >:
    public access::object_traits< ::User >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // firebaseID
      //
      details::buffer firebaseID_value;
      std::size_t firebaseID_size;
      bool firebaseID_null;

      // lat
      //
      double lat_value;
      bool lat_null;

      // lng
      //
      double lng_value;
      bool lng_null;

      // minMagPreference
      //
      double minMagPreference_value;
      bool minMagPreference_null;

      // maxDistancePreference
      //
      double maxDistancePreference_value;
      bool maxDistancePreference_null;

      // minMillisNotificationDelay
      //
      long long minMillisNotificationDelay_value;
      bool minMillisNotificationDelay_null;

      // lastNotificationMillis
      //
      long long lastNotificationMillis_value;
      bool lastNotificationMillis_null;

      // receiveRealTimeNotification
      //
      long long receiveRealTimeNotification_value;
      bool receiveRealTimeNotification_null;

      // lastModify
      //
      long long lastModify_value;
      bool lastModify_null;

      // secretKey
      //
      details::buffer secretKey_value;
      std::size_t secretKey_size;
      bool secretKey_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 11UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::User, id_common >:
    public access::object_traits_impl< ::User, id_sqlite >
  {
  };

  // User
  //
}

#include "User-odb.ixx"

#include <odb/post.hxx>

#endif // USER_ODB_HPP
