//
// Created by nicomazz97 on 20/11/16.
//

#ifndef SIMPLE_WEB_SERVER_USER_H
#define SIMPLE_WEB_SERVER_USER_H

#include <odb/core.hxx>
#include <string>

#pragma db object
class User {
public:
    User(){id = -1;}
#pragma db id auto
    long id;
    std::string firebaseID; // corrispondente al firebase id
    double lat;
    double lng;

    double minMagPreference;
    double maxDistancePreference;
    long minMillisNotificationDelay;

    long lastNotificationMillis;

    bool receiveRealTimeNotification;

    long lastModify;

    // todo generate secret key
    std::string secretKey; // key to update the information or send the reports, autogenerated on user creation


};


#endif //SIMPLE_WEB_SERVER_USER_H
