// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DBREPORT_ODB_HPP
#define DBREPORT_ODB_HPP

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "DBReport.hpp"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // DBReport
  //
  template <>
  struct class_traits< ::DBReport >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBReport >
  {
    public:
    typedef ::DBReport object_type;
    typedef ::DBReport* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // DBReport
  //
  template <typename A>
  struct query_columns< ::DBReport, id_sqlite, A >
  {
    // millis
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    millis_type_;

    static const millis_type_ millis;

    // user_id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    user_id_type_;

    static const user_id_type_ user_id;

    // power
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    power_type_;

    static const power_type_ power;

    // lat
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    lat_type_;

    static const lat_type_ lat;

    // lng
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    lng_type_;

    static const lng_type_ lng;
  };

  template <typename A>
  const typename query_columns< ::DBReport, id_sqlite, A >::millis_type_
  query_columns< ::DBReport, id_sqlite, A >::
  millis (A::table_name, "\"millis\"", 0);

  template <typename A>
  const typename query_columns< ::DBReport, id_sqlite, A >::user_id_type_
  query_columns< ::DBReport, id_sqlite, A >::
  user_id (A::table_name, "\"user_id\"", 0);

  template <typename A>
  const typename query_columns< ::DBReport, id_sqlite, A >::power_type_
  query_columns< ::DBReport, id_sqlite, A >::
  power (A::table_name, "\"power\"", 0);

  template <typename A>
  const typename query_columns< ::DBReport, id_sqlite, A >::lat_type_
  query_columns< ::DBReport, id_sqlite, A >::
  lat (A::table_name, "\"lat\"", 0);

  template <typename A>
  const typename query_columns< ::DBReport, id_sqlite, A >::lng_type_
  query_columns< ::DBReport, id_sqlite, A >::
  lng (A::table_name, "\"lng\"", 0);

  template <typename A>
  struct pointer_query_columns< ::DBReport, id_sqlite, A >:
    query_columns< ::DBReport, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::DBReport, id_sqlite >:
    public access::object_traits< ::DBReport >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // millis
      //
      long long millis_value;
      bool millis_null;

      // user_id
      //
      long long user_id_value;
      bool user_id_null;

      // power
      //
      long long power_value;
      bool power_null;

      // lat
      //
      double lat_value;
      bool lat_null;

      // lng
      //
      double lng_value;
      bool lng_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBReport, id_common >:
    public access::object_traits_impl< ::DBReport, id_sqlite >
  {
  };

  // DBReport
  //
}

#include "DBReport-odb.ixx"

#include <odb/post.hxx>

#endif // DBREPORT_ODB_HPP
