// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "Event-odb.hpp"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // Event
  //

  struct access::object_traits_impl< ::Event, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::Event, id_sqlite >::id_type
  access::object_traits_impl< ::Event, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Event, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = false;

    // date
    //
    if (t[1UL])
    {
      i.date_value.capacity (i.date_size);
      grew = true;
    }

    // depthKm
    //
    t[2UL] = false;

    // author
    //
    if (t[3UL])
    {
      i.author_value.capacity (i.author_size);
      grew = true;
    }

    // catalog
    //
    if (t[4UL])
    {
      i.catalog_value.capacity (i.catalog_size);
      grew = true;
    }

    // contributor
    //
    if (t[5UL])
    {
      i.contributor_value.capacity (i.contributor_size);
      grew = true;
    }

    // contributorId
    //
    if (t[6UL])
    {
      i.contributorId_value.capacity (i.contributorId_size);
      grew = true;
    }

    // magType
    //
    if (t[7UL])
    {
      i.magType_value.capacity (i.magType_size);
      grew = true;
    }

    // magnitude
    //
    t[8UL] = false;

    // magAuthor
    //
    if (t[9UL])
    {
      i.magAuthor_value.capacity (i.magAuthor_size);
      grew = true;
    }

    // eventLocation
    //
    if (t[10UL])
    {
      i.eventLocation_value.capacity (i.eventLocation_size);
      grew = true;
    }

    // millis
    //
    t[11UL] = false;

    // lat
    //
    t[12UL] = false;

    // lng
    //
    t[13UL] = false;

    // isRealTimeReport
    //
    t[14UL] = false;

    // numberOfReports
    //
    t[15UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::Event, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // date
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.date_value.data ();
    b[n].size = &i.date_size;
    b[n].capacity = i.date_value.capacity ();
    b[n].is_null = &i.date_null;
    n++;

    // depthKm
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.depthKm_value;
    b[n].is_null = &i.depthKm_null;
    n++;

    // author
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.author_value.data ();
    b[n].size = &i.author_size;
    b[n].capacity = i.author_value.capacity ();
    b[n].is_null = &i.author_null;
    n++;

    // catalog
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.catalog_value.data ();
    b[n].size = &i.catalog_size;
    b[n].capacity = i.catalog_value.capacity ();
    b[n].is_null = &i.catalog_null;
    n++;

    // contributor
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.contributor_value.data ();
    b[n].size = &i.contributor_size;
    b[n].capacity = i.contributor_value.capacity ();
    b[n].is_null = &i.contributor_null;
    n++;

    // contributorId
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.contributorId_value.data ();
    b[n].size = &i.contributorId_size;
    b[n].capacity = i.contributorId_value.capacity ();
    b[n].is_null = &i.contributorId_null;
    n++;

    // magType
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.magType_value.data ();
    b[n].size = &i.magType_size;
    b[n].capacity = i.magType_value.capacity ();
    b[n].is_null = &i.magType_null;
    n++;

    // magnitude
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.magnitude_value;
    b[n].is_null = &i.magnitude_null;
    n++;

    // magAuthor
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.magAuthor_value.data ();
    b[n].size = &i.magAuthor_size;
    b[n].capacity = i.magAuthor_value.capacity ();
    b[n].is_null = &i.magAuthor_null;
    n++;

    // eventLocation
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.eventLocation_value.data ();
    b[n].size = &i.eventLocation_size;
    b[n].capacity = i.eventLocation_value.capacity ();
    b[n].is_null = &i.eventLocation_null;
    n++;

    // millis
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.millis_value;
    b[n].is_null = &i.millis_null;
    n++;

    // lat
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.lat_value;
    b[n].is_null = &i.lat_null;
    n++;

    // lng
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.lng_value;
    b[n].is_null = &i.lng_null;
    n++;

    // isRealTimeReport
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.isRealTimeReport_value;
    b[n].is_null = &i.isRealTimeReport_null;
    n++;

    // numberOfReports
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.numberOfReports_value;
    b[n].is_null = &i.numberOfReports_null;
    n++;
  }

  void access::object_traits_impl< ::Event, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Event, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      long int const& v =
        o.id;

      bool is_null (false);
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        v);
      i.id_null = is_null;
    }

    // date
    //
    {
      ::std::string const& v =
        o.date;

      bool is_null (false);
      std::size_t cap (i.date_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.date_value,
        i.date_size,
        is_null,
        v);
      i.date_null = is_null;
      grew = grew || (cap != i.date_value.capacity ());
    }

    // depthKm
    //
    {
      double const& v =
        o.depthKm;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.depthKm_value,
        is_null,
        v);
      i.depthKm_null = is_null;
    }

    // author
    //
    {
      ::std::string const& v =
        o.author;

      bool is_null (false);
      std::size_t cap (i.author_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.author_value,
        i.author_size,
        is_null,
        v);
      i.author_null = is_null;
      grew = grew || (cap != i.author_value.capacity ());
    }

    // catalog
    //
    {
      ::std::string const& v =
        o.catalog;

      bool is_null (false);
      std::size_t cap (i.catalog_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.catalog_value,
        i.catalog_size,
        is_null,
        v);
      i.catalog_null = is_null;
      grew = grew || (cap != i.catalog_value.capacity ());
    }

    // contributor
    //
    {
      ::std::string const& v =
        o.contributor;

      bool is_null (false);
      std::size_t cap (i.contributor_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.contributor_value,
        i.contributor_size,
        is_null,
        v);
      i.contributor_null = is_null;
      grew = grew || (cap != i.contributor_value.capacity ());
    }

    // contributorId
    //
    {
      ::std::string const& v =
        o.contributorId;

      bool is_null (false);
      std::size_t cap (i.contributorId_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.contributorId_value,
        i.contributorId_size,
        is_null,
        v);
      i.contributorId_null = is_null;
      grew = grew || (cap != i.contributorId_value.capacity ());
    }

    // magType
    //
    {
      ::std::string const& v =
        o.magType;

      bool is_null (false);
      std::size_t cap (i.magType_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.magType_value,
        i.magType_size,
        is_null,
        v);
      i.magType_null = is_null;
      grew = grew || (cap != i.magType_value.capacity ());
    }

    // magnitude
    //
    {
      double const& v =
        o.magnitude;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.magnitude_value,
        is_null,
        v);
      i.magnitude_null = is_null;
    }

    // magAuthor
    //
    {
      ::std::string const& v =
        o.magAuthor;

      bool is_null (false);
      std::size_t cap (i.magAuthor_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.magAuthor_value,
        i.magAuthor_size,
        is_null,
        v);
      i.magAuthor_null = is_null;
      grew = grew || (cap != i.magAuthor_value.capacity ());
    }

    // eventLocation
    //
    {
      ::std::string const& v =
        o.eventLocation;

      bool is_null (false);
      std::size_t cap (i.eventLocation_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.eventLocation_value,
        i.eventLocation_size,
        is_null,
        v);
      i.eventLocation_null = is_null;
      grew = grew || (cap != i.eventLocation_value.capacity ());
    }

    // millis
    //
    {
      long int const& v =
        o.millis;

      bool is_null (false);
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_image (
        i.millis_value,
        is_null,
        v);
      i.millis_null = is_null;
    }

    // lat
    //
    {
      double const& v =
        o.lat;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.lat_value,
        is_null,
        v);
      i.lat_null = is_null;
    }

    // lng
    //
    {
      double const& v =
        o.lng;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.lng_value,
        is_null,
        v);
      i.lng_null = is_null;
    }

    // isRealTimeReport
    //
    {
      bool const& v =
        o.isRealTimeReport;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.isRealTimeReport_value,
        is_null,
        v);
      i.isRealTimeReport_null = is_null;
    }

    // numberOfReports
    //
    {
      int const& v =
        o.numberOfReports;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.numberOfReports_value,
        is_null,
        v);
      i.numberOfReports_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::Event, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      long int& v =
        o.id;

      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // date
    //
    {
      ::std::string& v =
        o.date;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.date_value,
        i.date_size,
        i.date_null);
    }

    // depthKm
    //
    {
      double& v =
        o.depthKm;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.depthKm_value,
        i.depthKm_null);
    }

    // author
    //
    {
      ::std::string& v =
        o.author;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.author_value,
        i.author_size,
        i.author_null);
    }

    // catalog
    //
    {
      ::std::string& v =
        o.catalog;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.catalog_value,
        i.catalog_size,
        i.catalog_null);
    }

    // contributor
    //
    {
      ::std::string& v =
        o.contributor;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.contributor_value,
        i.contributor_size,
        i.contributor_null);
    }

    // contributorId
    //
    {
      ::std::string& v =
        o.contributorId;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.contributorId_value,
        i.contributorId_size,
        i.contributorId_null);
    }

    // magType
    //
    {
      ::std::string& v =
        o.magType;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.magType_value,
        i.magType_size,
        i.magType_null);
    }

    // magnitude
    //
    {
      double& v =
        o.magnitude;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.magnitude_value,
        i.magnitude_null);
    }

    // magAuthor
    //
    {
      ::std::string& v =
        o.magAuthor;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.magAuthor_value,
        i.magAuthor_size,
        i.magAuthor_null);
    }

    // eventLocation
    //
    {
      ::std::string& v =
        o.eventLocation;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.eventLocation_value,
        i.eventLocation_size,
        i.eventLocation_null);
    }

    // millis
    //
    {
      long int& v =
        o.millis;

      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_value (
        v,
        i.millis_value,
        i.millis_null);
    }

    // lat
    //
    {
      double& v =
        o.lat;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.lat_value,
        i.lat_null);
    }

    // lng
    //
    {
      double& v =
        o.lng;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.lng_value,
        i.lng_null);
    }

    // isRealTimeReport
    //
    {
      bool& v =
        o.isRealTimeReport;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.isRealTimeReport_value,
        i.isRealTimeReport_null);
    }

    // numberOfReports
    //
    {
      int& v =
        o.numberOfReports;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.numberOfReports_value,
        i.numberOfReports_null);
    }
  }

  void access::object_traits_impl< ::Event, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Event, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Event\" "
  "(\"id\", "
  "\"date\", "
  "\"depthKm\", "
  "\"author\", "
  "\"catalog\", "
  "\"contributor\", "
  "\"contributorId\", "
  "\"magType\", "
  "\"magnitude\", "
  "\"magAuthor\", "
  "\"eventLocation\", "
  "\"millis\", "
  "\"lat\", "
  "\"lng\", "
  "\"isRealTimeReport\", "
  "\"numberOfReports\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Event, id_sqlite >::find_statement[] =
  "SELECT "
  "\"Event\".\"id\", "
  "\"Event\".\"date\", "
  "\"Event\".\"depthKm\", "
  "\"Event\".\"author\", "
  "\"Event\".\"catalog\", "
  "\"Event\".\"contributor\", "
  "\"Event\".\"contributorId\", "
  "\"Event\".\"magType\", "
  "\"Event\".\"magnitude\", "
  "\"Event\".\"magAuthor\", "
  "\"Event\".\"eventLocation\", "
  "\"Event\".\"millis\", "
  "\"Event\".\"lat\", "
  "\"Event\".\"lng\", "
  "\"Event\".\"isRealTimeReport\", "
  "\"Event\".\"numberOfReports\" "
  "FROM \"Event\" "
  "WHERE \"Event\".\"id\"=?";

  const char access::object_traits_impl< ::Event, id_sqlite >::update_statement[] =
  "UPDATE \"Event\" "
  "SET "
  "\"date\"=?, "
  "\"depthKm\"=?, "
  "\"author\"=?, "
  "\"catalog\"=?, "
  "\"contributor\"=?, "
  "\"contributorId\"=?, "
  "\"magType\"=?, "
  "\"magnitude\"=?, "
  "\"magAuthor\"=?, "
  "\"eventLocation\"=?, "
  "\"millis\"=?, "
  "\"lat\"=?, "
  "\"lng\"=?, "
  "\"isRealTimeReport\"=?, "
  "\"numberOfReports\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::Event, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Event\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::Event, id_sqlite >::query_statement[] =
  "SELECT "
  "\"Event\".\"id\", "
  "\"Event\".\"date\", "
  "\"Event\".\"depthKm\", "
  "\"Event\".\"author\", "
  "\"Event\".\"catalog\", "
  "\"Event\".\"contributor\", "
  "\"Event\".\"contributorId\", "
  "\"Event\".\"magType\", "
  "\"Event\".\"magnitude\", "
  "\"Event\".\"magAuthor\", "
  "\"Event\".\"eventLocation\", "
  "\"Event\".\"millis\", "
  "\"Event\".\"lat\", "
  "\"Event\".\"lng\", "
  "\"Event\".\"isRealTimeReport\", "
  "\"Event\".\"numberOfReports\" "
  "FROM \"Event\"";

  const char access::object_traits_impl< ::Event, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Event\"";

  const char access::object_traits_impl< ::Event, id_sqlite >::table_name[] =
  "\"Event\"";

  void access::object_traits_impl< ::Event, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Event, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Event, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Event, id_sqlite >::pointer_type
  access::object_traits_impl< ::Event, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Event, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Event, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Event, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Event, id_sqlite >::object_type >
  access::object_traits_impl< ::Event, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Event, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"Event\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"Event\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"date\" TEXT NOT NULL,\n"
                      "  \"depthKm\" REAL NULL,\n"
                      "  \"author\" TEXT NOT NULL,\n"
                      "  \"catalog\" TEXT NOT NULL,\n"
                      "  \"contributor\" TEXT NOT NULL,\n"
                      "  \"contributorId\" TEXT NOT NULL,\n"
                      "  \"magType\" TEXT NOT NULL,\n"
                      "  \"magnitude\" REAL NULL,\n"
                      "  \"magAuthor\" TEXT NOT NULL,\n"
                      "  \"eventLocation\" TEXT NOT NULL,\n"
                      "  \"millis\" INTEGER NOT NULL,\n"
                      "  \"lat\" REAL NULL,\n"
                      "  \"lng\" REAL NULL,\n"
                      "  \"isRealTimeReport\" INTEGER NOT NULL,\n"
                      "  \"numberOfReports\" INTEGER NOT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
